// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFy1Xk0vM8_TApSirhbo9bwMcsfDKolwc',
    appId: '1:624627209217:android:eb1b99c4fb69f2d43c5c00',
    messagingSenderId: '624627209217',
    projectId: 'tiktok-clone-app-9bc87',
    storageBucket: 'tiktok-clone-app-9bc87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDo2PCAV82Y0EtGfgMYdNvXYBWE5u3Vk8',
    appId: '1:624627209217:ios:fe62520ffb38ba863c5c00',
    messagingSenderId: '624627209217',
    projectId: 'tiktok-clone-app-9bc87',
    storageBucket: 'tiktok-clone-app-9bc87.firebasestorage.app',
    iosBundleId: 'com.example.tiktokCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDo2PCAV82Y0EtGfgMYdNvXYBWE5u3Vk8',
    appId: '1:624627209217:ios:fe62520ffb38ba863c5c00',
    messagingSenderId: '624627209217',
    projectId: 'tiktok-clone-app-9bc87',
    storageBucket: 'tiktok-clone-app-9bc87.firebasestorage.app',
    iosBundleId: 'com.example.tiktokCloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7t2qzme9rOW7USeyGbTYWsy4c7yXh_YI',
    appId: '1:624627209217:web:c50a33df66289b3c3c5c00',
    messagingSenderId: '624627209217',
    projectId: 'tiktok-clone-app-9bc87',
    authDomain: 'tiktok-clone-app-9bc87.firebaseapp.com',
    storageBucket: 'tiktok-clone-app-9bc87.firebasestorage.app',
    measurementId: 'G-YEQNE4HFT3',
  );

}